using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json;

namespace MyJournalProject.Entities;

// Entity class representing a Journal entry in the database

public class Journal
{
    // Primary key - unique identifier for the journal entry
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto-generated by database
    public int Id { get; set; }

    // Foreign key to the User table - identifies which user owns this journal
    [Required]
    [ForeignKey("User")]
    public int UserId { get; set; }

    // Title of the journal entry (required with maximum length)
    [Required]
    [StringLength(200, ErrorMessage = "Title cannot exceed 200 characters")]
    public string Title { get; set; } = string.Empty;

    // Main content/body of the journal entry 
    [Required]
    public string Content { get; set; } = string.Empty;

    // Mood tracking fields for emotional state recording

    // Primary mood - main emotional state (required)
    [Required]
    [StringLength(50)] // Database column size constraint
    public string PrimaryMood { get; set; } = string.Empty;

    // Optional secondary moods - additional emotional states
    [StringLength(50)]
    public string? SecondaryMood1 { get; set; }

    [StringLength(50)]
    public string? SecondaryMood2 { get; set; }

    // Categorization field for organizing journals by type/theme
    [Required]
    [StringLength(100)]
    public string Category { get; set; } = "General"; // Default category

    // Tags stored as JSON array in the database
    // JSON format allows for flexible tag storage without separate table
    public string TagsJson { get; set; } = "[]"; // Default empty JSON array

    // NotMapped property - not stored directly in database, derived from TagsJson
    // Provides easy access to tags as List<string> while storing as JSON
    [NotMapped]
    public List<string> Tags
    {
        get => JsonSerializer.Deserialize<List<string>>(TagsJson ?? "[]") ?? new List<string>();
        set => TagsJson = JsonSerializer.Serialize(value);
    }

    // Statistics fields for analytics and insights

    // Word count of the journal content (calculated during save)
    public int WordCount { get; set; } = 0;

    // Character count of the journal content (calculated during save)
    public int CharacterCount { get; set; } = 0;

    // Dates for tracking and organizing

    // The date the journal entry is for (defaults to today)
    [Required]
    public DateTime EntryDate { get; set; } = DateTime.Today;

    // When the journal was created
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // When the journal was last updated 
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Navigation property - EF Core uses this for relationship mapping
    // Virtual enables lazy loading )
    public virtual User? User { get; set; }
}