using Microsoft.EntityFrameworkCore;
using MyJournalProject.Entities;

namespace MyJournalProject.Data;

// Database context class for Entity Framework Core
public class AppDbContext : DbContext
{
    // DbSet properties represent tables in the database

    // Users table - stores user account information
    public DbSet<User> Users { get; set; }

    // Journals table - stores journal entries
    public DbSet<Journal> Journals { get; set; }

    // Constructor - accepts DbContextOptions for configuration
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
        try
        {
            // Ensure database is created (if it doesn't exist)
            // This creates the database and applies migrations on first run
            Database.EnsureCreated();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error creating database: {ex.Message}");
        }
    }

    // Configure the database model (schema, relationships, constraints)
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // User entity configuration
        modelBuilder.Entity<User>(entity =>
        {
            // Set primary key
            entity.HasKey(e => e.Id);

            // Configure Id to be auto-generated by database
            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            // Configure FullName column
            entity.Property(e => e.FullName)
                .IsRequired() // Cannot be null
                .HasMaxLength(200); // Maximum length constraint

            // Configure Email column
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200);

            // Configure Password column (stores SHA256 hash)
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(256); // SHA256 hash is 64 hex characters

            // Configure CreatedAt with SQL default value
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP"); // Database sets timestamp on insert

            // Create unique index on Email to prevent duplicate accounts
            entity.HasIndex(e => e.Email)
                  .IsUnique();
        });

        // Journal entity configuration
        modelBuilder.Entity<Journal>(entity =>
        {
            // Set primary key
            entity.HasKey(e => e.Id);
            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            // Configure Title column
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            // Configure Content column (no length limit for rich text)
            entity.Property(e => e.Content)
                .IsRequired();

            // Configure mood columns
            entity.Property(e => e.PrimaryMood)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.SecondaryMood1)
                .HasMaxLength(50);

            entity.Property(e => e.SecondaryMood2)
                .HasMaxLength(50);

            // Configure Category with default value
            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(100)
                .HasDefaultValue("General");

            // Configure TagsJson with default empty array
            entity.Property(e => e.TagsJson)
                .HasDefaultValue("[]");

            // Configure EntryDate (required)
            entity.Property(e => e.EntryDate)
                .IsRequired();

            // Configure timestamps with SQL defaults
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            // Configure foreign key relationship to User
            // Each journal belongs to one user
            entity.HasOne(j => j.User)
                  .WithMany() // A user can have many journals
                  .HasForeignKey(j => j.UserId)
                  .OnDelete(DeleteBehavior.Cascade); // Delete journals when user is deleted

            // Create unique composite index to enforce one journal per user per day
            // Prevents users from creating multiple journals on the same date
            entity.HasIndex(j => new { j.UserId, j.EntryDate })
                  .IsUnique()
                  .HasDatabaseName("IX_Journal_UserId_EntryDate");
        });
    }
}